version: '3.8'

services:
  backend-staging:
    image: registry.gitlab.com/migin165/project1/backend:staging
    container_name: game-backend-staging
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=staging
      - SERVER_PORT=8080
      - cors.allowed.origins=http://152.42.196.25:3001,http://localhost:3001
      - CORS_ALLOWED_ORIGINS=http://152.42.196.25:3001,http://localhost:3001
    volumes:
      - /opt/game/data:/app/data
      - ./logs/backend/staging:/app/logs
    networks:
      - game-network-staging

  frontend-staging:
    image: registry.gitlab.com/migin165/project1/frontend:staging
    container_name: game-frontend-staging
    restart: unless-stopped
    ports:
      - "3001:80"
    environment:
      - REACT_APP_API_URL=http://152.42.196.25:8081
    depends_on:
      - backend-staging
    networks:
      - game-network-staging

networks:
  game-network-staging:
    driver: bridge
    name: game-staging-network